fmac-y := fmac/procfs.o fmac/check.o
fmac-y += capraise.o allowlist.o totp.o check.o anonfd.o nksu.o kprobe.o

obj-$(CONFIG_FMAC) += fmac.o

KDIR := $(KDIR)
MDIR := $(realpath $(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
IDIR := $(MDIR)/include

ccflags-y += -I$(srctree)/security/selinux -I$(srctree)/security/selinux/include
ccflags-y += -I$(IDIR)
ccflags-y += -I$(objtree)/security/selinux -include $(srctree)/include/uapi/asm-generic/errno.h
